# Generated by Django 6.0.5 on 2026-05-27 06:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(blank=True, help_text='Иконка FontAwesome (например, fa-book)', max_length=50, verbose_name='Иконка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='wiki.wikicategory', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WikiArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('excerpt', models.TextField(blank=True, help_text='Краткое описание для превью', verbose_name='Анонс')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('is_featured', models.BooleanField(default=False, help_text='Показывать на главной странице', verbose_name='Избранное')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_articles', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('parent_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_articles', to='wiki.wikiarticle', verbose_name='Родительская статья')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='wiki.wikicategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-is_featured', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WikiAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='wiki_attachments/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='wiki.wikiarticle', verbose_name='Статья')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['article', '-uploaded_at'], name='wiki_wikiat_article_f2e331_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='wikicategory',
            index=models.Index(fields=['slug'], name='wiki_wikica_slug_3e4a71_idx'),
        ),
        migrations.AddIndex(
            model_name='wikicategory',
            index=models.Index(fields=['parent'], name='wiki_wikica_parent__a6dc2f_idx'),
        ),
        migrations.AddIndex(
            model_name='wikiarticle',
            index=models.Index(fields=['slug'], name='wiki_wikiar_slug_06bef9_idx'),
        ),
        migrations.AddIndex(
            model_name='wikiarticle',
            index=models.Index(fields=['category', '-updated_at'], name='wiki_wikiar_categor_fb1375_idx'),
        ),
        migrations.AddIndex(
            model_name='wikiarticle',
            index=models.Index(fields=['is_published', '-updated_at'], name='wiki_wikiar_is_publ_695645_idx'),
        ),
        migrations.AddIndex(
            model_name='wikiarticle',
            index=models.Index(fields=['-views'], name='wiki_wikiar_views_53626a_idx'),
        ),
    ]
