# Generated by Django 5.0.14 on 2025-11-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_caldavsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalsettings',
            name='document_storage_type',
            field=models.CharField(choices=[('local', 'Локальный диск (внутреннее хранилище)'), ('s3', 'S3-совместимое хранилище')], default='local', help_text='Выберите, где хранить файлы документов: на локальном диске или во внешнем S3-совместимом хранилище.', max_length=20, verbose_name='Тип хранилища документов'),
        ),
        migrations.AddField(
            model_name='portalsettings',
            name='s3_access_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='S3 Access Key'),
        ),
        migrations.AddField(
            model_name='portalsettings',
            name='s3_bucket_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='S3 Bucket'),
        ),
        migrations.AddField(
            model_name='portalsettings',
            name='s3_endpoint_url',
            field=models.URLField(blank=True, help_text='Адрес S3-совместимого хранилища (например, https://s3.example.com). Используется, если выбран тип S3.', null=True, verbose_name='S3 Endpoint URL'),
        ),
        migrations.AddField(
            model_name='portalsettings',
            name='s3_secret_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='S3 Secret Key'),
        ),
    ]
