# Generated by Django 5.0.14 on 2025-11-16 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_unit_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='parent_department',
            field=models.ForeignKey(blank=True, help_text='Выберите департамент, которому подчинён данный департамент.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_departments', to='organization.department', verbose_name='Родительский департамент'),
        ),
    ]
