# Generated by Django 5.0.14 on 2025-11-18 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def clean_vacation_request_fields(apps, schema_editor):
    """
    Очищает пустые строки в полях department, unit, position перед преобразованием в ForeignKey.
    Заменяет пустые строки на NULL используя SQL напрямую.
    Проверяет существование колонок перед их изменением.
    """
    # Используем SQL напрямую, чтобы обойти ограничения NOT NULL
    with schema_editor.connection.cursor() as cursor:
        # Проверяем, какие колонки существуют
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'organization_vacationrequest' 
            AND column_name IN ('department', 'unit', 'position', 'department_old', 'unit_old', 'position_old')
        """)
        existing_columns = {row[0] for row in cursor.fetchall()}
        
        # Если колонки уже переименованы, значит миграция была частично применена - пропускаем очистку
        if 'department_old' in existing_columns or 'unit_old' in existing_columns or 'position_old' in existing_columns:
            return
        
        # Если колонок нет вообще, значит они уже преобразованы - пропускаем
        if 'department' not in existing_columns and 'unit' not in existing_columns and 'position' not in existing_columns:
            return
        
        # Сначала временно разрешаем NULL (если колонки существуют)
        if 'department' in existing_columns:
            cursor.execute("ALTER TABLE organization_vacationrequest ALTER COLUMN department DROP NOT NULL")
            cursor.execute("UPDATE organization_vacationrequest SET department = NULL WHERE department = ''")
        
        if 'unit' in existing_columns:
            cursor.execute("ALTER TABLE organization_vacationrequest ALTER COLUMN unit DROP NOT NULL")
            cursor.execute("UPDATE organization_vacationrequest SET unit = NULL WHERE unit = ''")
        
        if 'position' in existing_columns:
            cursor.execute("ALTER TABLE organization_vacationrequest ALTER COLUMN position DROP NOT NULL")
            cursor.execute("UPDATE organization_vacationrequest SET position = NULL WHERE position = ''")


def reverse_clean_vacation_request_fields(apps, schema_editor):
    """
    Обратная операция - заменяет NULL на пустые строки (если понадобится откат).
    """
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("UPDATE organization_vacationrequest SET department = '' WHERE department IS NULL;")
        cursor.execute("UPDATE organization_vacationrequest SET unit = '' WHERE unit IS NULL;")
        cursor.execute("UPDATE organization_vacationrequest SET position = '' WHERE position IS NULL;")
        # Восстанавливаем NOT NULL (если нужно)
        cursor.execute("ALTER TABLE organization_vacationrequest ALTER COLUMN department SET NOT NULL;")
        cursor.execute("ALTER TABLE organization_vacationrequest ALTER COLUMN unit SET NOT NULL;")
        cursor.execute("ALTER TABLE organization_vacationrequest ALTER COLUMN position SET NOT NULL;")


class Migration(migrations.Migration):
    # Отключаем атомарность для этой миграции, чтобы избежать конфликтов триггеров
    atomic = False

    dependencies = [
        ('organization', '0010_mattermostsettings_verify_ssl'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Используем SeparateDatabaseAndState для условного создания таблицы
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Условное создание таблицы Position (если таблица уже существует, пропускаем)
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS organization_position (
                            id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                            name varchar(255) NOT NULL UNIQUE,
                            created_at timestamp with time zone NOT NULL,
                            updated_at timestamp with time zone NOT NULL
                        );
                    """,
                    reverse_sql="DROP TABLE IF EXISTS organization_position;",
                ),
                # Создаем индексы, если их еще нет
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            IF NOT EXISTS (
                                SELECT 1 FROM pg_indexes 
                                WHERE tablename = 'organization_position' 
                                AND indexname = 'organization_position_name_key'
                            ) THEN
                                CREATE UNIQUE INDEX organization_position_name_key ON organization_position(name);
                            END IF;
                        END $$;
                    """,
                    reverse_sql="DROP INDEX IF EXISTS organization_position_name_key;",
                ),
            ],
            state_operations=[
                # Обновляем состояние Django, чтобы оно знало о модели Position
                migrations.CreateModel(
                    name='Position',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(help_text='Например: Менеджер по продажам, Разработчик, Директор и т.д.', max_length=255, unique=True, verbose_name='Название должности')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                        ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                    ],
                    options={
                        'verbose_name': 'Должность',
                        'verbose_name_plural': 'Должности',
                        'ordering': ['name'],
                    },
                ),
            ],
        ),
        migrations.AlterField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, help_text='Выберите руководителя из таблицы руководителей департаментов.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель департамента'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='head',
            field=models.ForeignKey(blank=True, help_text='Выберите руководителя из таблицы руководителей отделов.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_units', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель отдела'),
        ),
        # Очищаем пустые строки перед преобразованием в ForeignKey
        migrations.RunPython(clean_vacation_request_fields, reverse_clean_vacation_request_fields),
        # Используем RunSQL для преобразования полей в ForeignKey
        # Разделяем операции на отдельные шаги для избежания конфликтов триггеров
        # Проверяем существование колонок перед переименованием
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name = 'organization_vacationrequest' 
                        AND column_name = 'department'
                    ) THEN
                        ALTER TABLE organization_vacationrequest RENAME COLUMN department TO department_old;
                    END IF;
                END $$;
            """,
            reverse_sql="ALTER TABLE organization_vacationrequest RENAME COLUMN department_old TO department;",
        ),
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name = 'organization_vacationrequest' 
                        AND column_name = 'unit'
                    ) THEN
                        ALTER TABLE organization_vacationrequest RENAME COLUMN unit TO unit_old;
                    END IF;
                END $$;
            """,
            reverse_sql="ALTER TABLE organization_vacationrequest RENAME COLUMN unit_old TO unit;",
        ),
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name = 'organization_vacationrequest' 
                        AND column_name = 'position'
                    ) THEN
                        ALTER TABLE organization_vacationrequest RENAME COLUMN position TO position_old;
                    END IF;
                END $$;
            """,
            reverse_sql="ALTER TABLE organization_vacationrequest RENAME COLUMN position_old TO position;",
        ),
        # Создаем новые поля как ForeignKey (если их еще нет)
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name = 'organization_vacationrequest' 
                        AND column_name = 'department_id'
                    ) THEN
                        ALTER TABLE organization_vacationrequest 
                        ADD COLUMN department_id INTEGER NULL REFERENCES organization_department(id) ON DELETE SET NULL;
                    END IF;
                END $$;
            """,
            reverse_sql="ALTER TABLE organization_vacationrequest DROP COLUMN IF EXISTS department_id;",
        ),
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name = 'organization_vacationrequest' 
                        AND column_name = 'unit_id'
                    ) THEN
                        ALTER TABLE organization_vacationrequest 
                        ADD COLUMN unit_id INTEGER NULL REFERENCES organization_unit(id) ON DELETE SET NULL;
                    END IF;
                END $$;
            """,
            reverse_sql="ALTER TABLE organization_vacationrequest DROP COLUMN IF EXISTS unit_id;",
        ),
        migrations.RunSQL(
            sql="""
                DO $$
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name = 'organization_vacationrequest' 
                        AND column_name = 'position_id'
                    ) THEN
                        ALTER TABLE organization_vacationrequest 
                        ADD COLUMN position_id INTEGER NULL REFERENCES organization_position(id) ON DELETE SET NULL;
                    END IF;
                END $$;
            """,
            reverse_sql="ALTER TABLE organization_vacationrequest DROP COLUMN IF EXISTS position_id;",
        ),
        # Удаляем старые поля (если они существуют)
        migrations.RunSQL(
            sql="ALTER TABLE organization_vacationrequest DROP COLUMN IF EXISTS department_old;",
            reverse_sql="ALTER TABLE organization_vacationrequest ADD COLUMN department VARCHAR(255) NOT NULL DEFAULT '';",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE organization_vacationrequest DROP COLUMN IF EXISTS unit_old;",
            reverse_sql="ALTER TABLE organization_vacationrequest ADD COLUMN unit VARCHAR(255) NOT NULL DEFAULT '';",
        ),
        migrations.RunSQL(
            sql="ALTER TABLE organization_vacationrequest DROP COLUMN IF EXISTS position_old;",
            reverse_sql="ALTER TABLE organization_vacationrequest ADD COLUMN position VARCHAR(255) NOT NULL DEFAULT '';",
        ),
        # Обновляем состояние Django моделей (без изменения базы данных, так как мы уже сделали это через SQL)
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # База данных уже обновлена через SQL выше
            state_operations=[
                migrations.AlterField(
                    model_name='vacationrequest',
                    name='department',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacation_requests', to='organization.department', verbose_name='Департамент'),
                ),
                migrations.AlterField(
                    model_name='vacationrequest',
                    name='unit',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacation_requests', to='organization.unit', verbose_name='Отдел'),
                ),
                migrations.AlterField(
                    model_name='vacationrequest',
                    name='position',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacation_requests', to='organization.position', verbose_name='Должность'),
                ),
            ],
        ),
    ]
