# Generated by Django 6.0.5 on 2026-05-27 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('color', models.CharField(default='#4f46e5', help_text='Hex цвет', max_length=7, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Категория новостей',
                'verbose_name_plural': 'Категории новостей',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('excerpt', models.TextField(blank=True, help_text='Краткое описание', verbose_name='Анонс')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Изображение')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('is_pinned', models.BooleanField(default=False, help_text='Закрепить вверху списка', verbose_name='Закреплено')),
                ('send_email', models.BooleanField(default=False, help_text='Отправить уведомление по email', verbose_name='Отправить email')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_articles', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='news.newscategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-is_pinned', '-published_at', '-created_at'],
                'indexes': [models.Index(fields=['-is_pinned', '-published_at'], name='news_news_is_pinn_3d06a5_idx'), models.Index(fields=['is_published', '-published_at'], name='news_news_is_publ_dcad2b_idx')],
            },
        ),
    ]
