source 'https://rubygems.org'

# Укажите зависимости плагина здесь
gem 'json', '~> 2.3.0'

# Для тестирования
group :test do
  gem 'rspec', '~> 3.10'
  gem 'rspec-rails', '~> 4.0'
end

# Для разработки
group :development do
  gem 'rubocop', '~> 1.18.0'
end