# Generated by Django 5.0.14 on 2025-11-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_manager_userprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_news_moderator',
            field=models.BooleanField(default=False, help_text='Если отмечено, пользователь может создавать и публиковать корпоративные новости.', verbose_name='Модератор новостей'),
        ),
    ]
