# Generated by Django 5.0.14 on 2025-11-18 09:32

import django.db.models.deletion
from django.db import migrations, models


def clean_userprofile_fields(apps, schema_editor):
    """
    Очищает пустые строки в полях department, unit, position перед преобразованием в ForeignKey.
    Заменяет пустые строки на NULL используя SQL напрямую.
    """
    # Используем SQL напрямую, чтобы обойти ограничения NOT NULL (если они есть)
    with schema_editor.connection.cursor() as cursor:
        # Проверяем, есть ли ограничение NOT NULL, и временно снимаем его
        try:
            cursor.execute("ALTER TABLE accounts_userprofile ALTER COLUMN department DROP NOT NULL;")
        except Exception:
            pass  # Если ограничения нет, продолжаем
        try:
            cursor.execute("ALTER TABLE accounts_userprofile ALTER COLUMN unit DROP NOT NULL;")
        except Exception:
            pass
        try:
            cursor.execute("ALTER TABLE accounts_userprofile ALTER COLUMN position DROP NOT NULL;")
        except Exception:
            pass
        # Затем заменяем пустые строки на NULL
        cursor.execute("UPDATE accounts_userprofile SET department = NULL WHERE department = '';")
        cursor.execute("UPDATE accounts_userprofile SET unit = NULL WHERE unit = '';")
        cursor.execute("UPDATE accounts_userprofile SET position = NULL WHERE position = '';")


def reverse_clean_userprofile_fields(apps, schema_editor):
    """
    Обратная операция - заменяет NULL на пустые строки (если понадобится откат).
    """
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("UPDATE accounts_userprofile SET department = '' WHERE department IS NULL;")
        cursor.execute("UPDATE accounts_userprofile SET unit = '' WHERE unit IS NULL;")
        cursor.execute("UPDATE accounts_userprofile SET position = '' WHERE position IS NULL;")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_mattermost'),
        ('organization', '0011_position_alter_department_head_alter_unit_head_and_more'),
    ]

    operations = [
        # Очищаем пустые строки перед преобразованием в ForeignKey
        migrations.RunPython(clean_userprofile_fields, reverse_clean_userprofile_fields),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Выберите департамент из списка департаментов.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_employees', to='organization.department', verbose_name='Департамент'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.ForeignKey(blank=True, help_text='Выберите должность из справочника должностей.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_employees', to='organization.position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Выберите отдел из списка отделов.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_employees', to='organization.unit', verbose_name='Отдел'),
        ),
    ]
