# Generated by Django 6.0.5 on 2026-05-27 06:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('capacity', models.PositiveIntegerField(default=10, help_text='Максимальное количество участников', verbose_name='Вместимость')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='Местоположение')),
                ('has_video_conf', models.BooleanField(default=True, verbose_name='Видеоконференция')),
                ('has_projector', models.BooleanField(default=False, verbose_name='Проектор')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Переговорная комната',
                'verbose_name_plural': 'Переговорные комнаты',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'capacity'], name='meetings_me_is_acti_cd7816_idx')],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('start_time', models.DateTimeField(verbose_name='Начало')),
                ('end_time', models.DateTimeField(verbose_name='Окончание')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('scheduled', 'Запланирована'), ('in_progress', 'Идет'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='draft', max_length=20, verbose_name='Статус')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Повторяющаяся')),
                ('recurrence_pattern', models.CharField(blank=True, choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], max_length=20, verbose_name='Паттерн повторения')),
                ('meeting_link', models.URLField(blank=True, help_text='Ссылка на видеоконференцию', verbose_name='Ссылка на встречу')),
                ('caldav_uid', models.CharField(blank=True, help_text='UID в CalDAV календаре', max_length=500, verbose_name='CalDAV UID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Организатор')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='meetings.meetingroom', verbose_name='Переговорная')),
            ],
            options={
                'verbose_name': 'Встреча',
                'verbose_name_plural': 'Встречи',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='MeetingAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='meeting_attachments/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='meetings.meeting', verbose_name='Встреча')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['meeting', '-uploaded_at'], name='meetings_me_meeting_280420_idx')],
            },
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, help_text='Для внешних участников', max_length=254, verbose_name='Email')),
                ('response', models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принято'), ('declined', 'Отклонено'), ('tentative', 'Возможно')], default='pending', max_length=20, verbose_name='Ответ')),
                ('joined_at', models.DateTimeField(blank=True, null=True, verbose_name='Присоединился')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='meetings.meeting', verbose_name='Встреча')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Участник встречи',
                'verbose_name_plural': 'Участники встреч',
                'ordering': ['response'],
                'indexes': [models.Index(fields=['meeting', 'response'], name='meetings_me_meeting_4878a5_idx'), models.Index(fields=['user', 'response'], name='meetings_me_user_id_2cf749_idx')],
                'unique_together': {('meeting', 'email'), ('meeting', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['status', 'start_time'], name='meetings_me_status_c95f40_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['organizer', '-start_time'], name='meetings_me_organiz_3e956f_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['start_time', 'end_time'], name='meetings_me_start_t_006dbd_idx'),
        ),
    ]
