"""
Django settings for corp_portal project.

Generated by 'django-admin startproject' using Django 5.0.14.

These settings are adapted for running inside Docker with environment-based
configuration for database and secret key.
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-dev-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'organization',
    'news',
    'tasks',
    'documents',
    'wiki',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'corp_portal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'organization.context_processors.portal_settings',
                'accounts.context_processors.user_theme',
                'accounts.context_processors.user_sidebar_settings',
                'accounts.context_processors.user_menu_settings',
                'accounts.context_processors.user_tasks_count',
                'accounts.context_processors.user_meetings_today_count',
                'accounts.context_processors.user_chat_notifications_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'corp_portal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'corp_portal'),
        'USER': os.getenv('POSTGRES_USER', 'corp_portal'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'corp_portal'),
        'HOST': os.getenv('POSTGRES_HOST', 'db'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Use Argon2 for secure password hashing
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Хранилище файлов документов (может быть примонтировано отдельным диском)
DATA_ROOT = BASE_DIR / 'data'

# Директория для временных файлов Mattermost (изображения и файлы из чатов)
MATTERMOST_FILES_ROOT = BASE_DIR / 'media' / 'mattermost_files'

# Тип хранилища документов по умолчанию.
# Может быть переопределён через переменную окружения DOCUMENT_STORAGE_TYPE
# или настройку в модели PortalSettings.
DOCUMENT_STORAGE_TYPE = os.getenv('DOCUMENT_STORAGE_TYPE', 'local')

# Параметры S3-совместимого хранилища (используются при выборе типа s3)
S3_ENDPOINT_URL = os.getenv('S3_ENDPOINT_URL', '')
S3_ACCESS_KEY = os.getenv('S3_ACCESS_KEY', '')
S3_SECRET_KEY = os.getenv('S3_SECRET_KEY', '')
S3_BUCKET_NAME = os.getenv('S3_BUCKET_NAME', '')


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email configuration (can be overridden via environment variables)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.example.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'no-reply@example.com')

# Auth redirects
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/account/profile/'
LOGOUT_REDIRECT_URL = '/'

# External URL для доступа к приложению извне (для OnlyOffice/Collabora)
# Если не задан, будет использоваться автоматическое определение из request
EXTERNAL_URL = os.getenv('EXTERNAL_URL', '')

# OnlyOffice integration
ONLYOFFICE_ENABLED = os.getenv('ONLYOFFICE_ENABLED', 'True') == 'True'
# OnlyOffice доступен через nginx с SSL на стандартном HTTPS порту 443
# Используется HTTPS с SSL сертификатом (самоподписанный для разработки)
# По умолчанию используется стандартный HTTPS порт 443 (не требует указания порта в URL)
ONLYOFFICE_BASE_URL = os.getenv('ONLYOFFICE_BASE_URL', 'https://localhost/')

# Collabora Online integration (альтернатива OnlyOffice)
COLLABORA_ENABLED = os.getenv('COLLABORA_ENABLED', 'False') == 'True'
# URL должен быть доступен из браузера, не из контейнера
COLLABORA_BASE_URL = os.getenv('COLLABORA_BASE_URL', 'http://localhost:9980')

