# Generated by Django 5.0.14 on 2026-05-27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MattermostProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mm_username', models.CharField(blank=True, max_length=100, verbose_name='Имя пользователя Mattermost')),
                ('mm_password', models.CharField(blank=True, max_length=255, verbose_name='Пароль Mattermost')),
                ('mm_token', models.CharField(blank=True, help_text='Персональный токен доступа (альтернатива паролю)', max_length=255, verbose_name='Токен доступа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна интеграция')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mattermost_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль Mattermost',
                'verbose_name_plural': 'Профили Mattermost',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Ключ')),
                ('value', models.TextField(verbose_name='Значение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_settings', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Системная настройка',
                'verbose_name_plural': 'Системные настройки',
                'ordering': ['key'],
            },
        ),
        migrations.AddIndex(
            model_name='mattermostprofile',
            index=models.Index(fields=['user'], name='settings_ma_user_id_idx'),
        ),
        migrations.AddIndex(
            model_name='mattermostprofile',
            index=models.Index(fields=['is_active'], name='settings_ma_is_acti_idx'),
        ),
        migrations.AddIndex(
            model_name='mattermostprofile',
            index=models.Index(fields=['mm_username'], name='settings_ma_mm_usern_idx'),
        ),
    ]
