# Generated by Django 6.0.5 on 2026-05-27 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mattermostprofile',
            new_name='settings_ma_user_id_d56c04_idx',
            old_name='settings_ma_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='mattermostprofile',
            new_name='settings_ma_is_acti_513f8d_idx',
            old_name='settings_ma_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='mattermostprofile',
            new_name='settings_ma_mm_user_f1cc8a_idx',
            old_name='settings_ma_mm_usern_idx',
        ),
    ]
