# Generated by Django 6.0.5 on 2026-05-27 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MattermostMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(db_index=True, max_length=200, verbose_name='Канал')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Отправлено')),
                ('success', models.BooleanField(db_index=True, default=False, verbose_name='Успешно')),
                ('response_data', models.TextField(blank=True, verbose_name='Ответ сервера')),
                ('response_time_ms', models.FloatField(blank=True, null=True, verbose_name='Время ответа (мс)')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mattermost_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Mattermost сообщение',
                'verbose_name_plural': 'Mattermost сообщения',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['channel', '-sent_at'], name='mattermost__channel_498a61_idx'), models.Index(fields=['success', '-sent_at'], name='mattermost__success_4a720c_idx'), models.Index(fields=['-sent_at'], name='mattermost__sent_at_39e95d_idx')],
            },
        ),
    ]
