apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: sa-token
  annotations:
    kubernetes.io/service-account.name: sa
type: kubernetes.io/service-account-token